### ISSUE TITLE
US15 - Criação da base da dados

### ISSUE THREAD

**Issue by juliolitwin** [fga-eps-mds/2021.1-PCTs-Documents-API#7]
## Descrição
Criação da base de dados para os documentos

## Tarefas
- [x] Criação dos Bancos de Dados.

## Critérios de aceitação
- [x] Deve ser possível realizar cadastro e atualização das fontes de dados

**Comment by caiovfernandes** [comment]
Issue fechada no PR:
https://github.com/fga-eps-mds/2021.1-PCTs-Documents-API/pull/8
